version: "3"

services:
  propertyspot_db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: REDACTED
      MYSQL_DATABASE: propertyspot
      MYSQL_USER: propertyspot
      MYSQL_PASSWORD: REDACTED
    container_name: propertyspot_db

  propertyspot:
    depends_on:
      - propertyspot_db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80
      - 443
    restart: always
    container_name: propertyspot_laravel
    volumes:
      - storage:/var/www/html/storage
      - cache:/var/www/html/bootstrap/cache
      - public:/var/www/html/public
    environment: 
      VIRTUAL_HOST: propertyspot.robotkudos.com
      LETSENCRYPT_HOST: propertyspot.robotkudos.com
      LETSENCRYPT_EMAIL: nhejazi@gmail.com

volumes:
  db_data:
  storage:
  cache:
  public:

networks:
  default:
    external:
      name: nginx-proxy
