version: "3"

services:
  propertyspot_db_test:
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - db_data_test:/var/lib/mysql
    restart: always
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: propertyspot
      MYSQL_USER: propertyspot
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: propertyspot_db_test

  propertyspot_test:
    depends_on:
      - propertyspot_db_test
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SSH_KEY=${SSH_KEY}
    ports:
      - 80
      - 443
    restart: always
    container_name: propertyspot_laravel_test

  selenium:
    image: selenium/standalone-chrome
    platform: linux/amd64
    shm_size: 2g
    ports:
      - 4444:4444
    container_name: propertyspot_selenium

volumes:
  db_data_test:

networks:
  default:
    external:
      name: nginx-proxy
