version: "3"

services:
  propertyspot_db:
    image: mysql:5.7
    volumes:
      - db_data_test:/var/lib/mysql
    restart: always
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: propertyspot
      MYSQL_DATABASE: propertyspot
      MYSQL_USER: propertyspot
      MYSQL_PASSWORD: REDACTED
    container_name: propertyspot_db_test

  propertyspot:
    depends_on:
      - propertyspot_db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80
      - 443
    restart: always
    container_name: propertyspot_laravel_test

  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    container_name: propertyspot_selenium

volumes:
  db_data_test:

networks:
  default:
    external:
      name: nginx-proxy
