version: "3"

services:
  propertyspot_db_test:
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: propertyspot
      MYSQL_DATABASE: propertyspot
      MYSQL_USER: propertyspot
      MYSQL_PASSWORD: REDACTED
    container_name: propertyspot_db

  propertyspot_test:
    depends_on:
      - propertyspot_db_test
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - 80
      - 443
    restart: always
    container_name: propertyspot_laravel
    volumes:
      - ./laravel:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/site.conf
      - ./php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
      
  selenium:
    image: selenium/standalone-chrome
    platform: linux/amd64
    ports:
      - 4444:4444
    container_name: propertyspot_selenium

volumes:
  db_data:

networks:
  default:
    external:
      name: nginx-proxy
