version: "3"

services:
  propertyspot_db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: REDACTED
      MYSQL_DATABASE: propertyspot
      MYSQL_USER: propertyspot
      MYSQL_PASSWORD: REDACTED
    container_name: propertyspot_db

  propertyspot:
    depends_on:
      - propertyspot_db
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - 80
      - 443
    restart: always
    container_name: propertyspot_laravel
    volumes:
      - ./laravel:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/site.conf
      - ./php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini

volumes:
  db_data:

networks:
  default:
    external:
      name: nginx-proxy
