FROM php:7.4-fpm
RUN apt-get update && \
    apt-get install -y nginx && \
    docker-php-ext-install bcmath && \
    docker-php-ext-install pdo_mysql && \
    apt-get install -y --no-install-recommends apt-utils && \
    apt-get install -y libmagickwand-dev libmagickcore-dev && \
    pecl install xdebug-2.8.1 && \
    docker-php-ext-enable xdebug && \
    pecl install imagick && \
    docker-php-ext-enable imagick && \
    apt-get install -y libzip-dev zip && \
    docker-php-ext-install zip && \
    apt-get install libjpeg-dev libpng-dev && \
    docker-php-ext-configure gd --with-jpeg && \
    docker-php-ext-install gd && \
    apt-get clean
COPY --from=composer /usr/bin/composer /usr/bin/composer
CMD service nginx start && \
    php-fpm
